/* WORLD KIT build stub: headless Blender never calls these. */
void xkb_compose_state_feed(void) {}
void xkb_compose_state_get_status(void) {}
void xkb_compose_state_get_utf8(void) {}
void xkb_compose_state_new(void) {}
void xkb_compose_state_reset(void) {}
void xkb_compose_state_unref(void) {}
void xkb_compose_table_new_from_locale(void) {}
void xkb_compose_table_unref(void) {}
void xkb_context_new(void) {}
void xkb_context_unref(void) {}
void xkb_keymap_key_repeats(void) {}
void xkb_keymap_mod_get_index(void) {}
void xkb_keymap_new_from_string(void) {}
void xkb_keymap_unref(void) {}
void xkb_state_get_keymap(void) {}
void xkb_state_key_get_one_sym(void) {}
void xkb_state_key_get_utf8(void) {}
void xkb_state_new(void) {}
void xkb_state_serialize_mods(void) {}
void xkb_state_unref(void) {}
void xkb_state_update_mask(void) {}
